services:
    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "app"
            MYSQL_DATABASE: "app"
            TZ: "Europe/Budapest"
        ports:
            - "3306:3306"
        volumes:
            - database_data:/var/lib/mysql:rw

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - database
        environment:
            - PMA_HOST=database

volumes:
    database_data:
